---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: teslamate
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: teslamate
    creationPolicy: Owner
  data:
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: teslamate
        property: encryption_key
    - secretKey: DATABASE_USER
      remoteRef:
        key: teslamate
        property: username
    - secretKey: DATABASE_NAME
      remoteRef:
        key: teslamate
        property: username
    - secretKey: DATABASE_PASS
      remoteRef:
        key: teslamate
        property: password
