apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd-charts.yaml
  - authelia-charts.yaml
  - bitnami-charts.yaml
  - bjw-s-charts.yaml
  - blakeshome-charts.yaml
  - botkubeio-charts.yaml
  - coredns-charts.yaml
  - csi-driver-nfs-charts.yaml
  - descheduler-charts.yaml
  - dysnix-charts.yaml
  - emqx.yaml
  - external-dns-charts.yaml
  - ./external-secrets.yaml
  - grafana-charts.yaml
  - hajimari-charts.yaml
  - ingress-nginx-charts.yaml
  - jetstack-charts.yaml
  - k8s-at-home-charts.yaml
  - k8s-gateway-charts.yaml
  - kubereboot-charts.yaml
  - kyverno-charts.yaml
  - lwolf-charts.yaml
  - metallb-charts.yaml
  - metrics-server-charts.yaml
  - prometheus-community-charts.yaml
  - rook-ceph-charts.yaml
  - runix.yaml
  - stakater-charts.yaml
  - vector-charts.yaml
  - weave-gitops-charts.yaml
  - xunholy-charts.yaml
