---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: unifi-poller
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: unifi-poller
    creationPolicy: Owner
  data:
    - secretKey: UP_UNIFI_DEFAULT_USER
      remoteRef:
        key: unifi-poller
        property: username
    - secretKey: UP_UNIFI_DEFAULT_PASS
      remoteRef:
        key: unifi-poller
        property: password
    - secretKey: UP_UNIFI_DEFAULT_URL
      remoteRef:
        key: unifi-poller
        property: url
