---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - bookstack
  - excalidraw
  - freshrss
  - hajimari
  - ./linkding
  - media-browser
  - reverse-proxy
  - weave-gitops
