---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #- remove-cpu-limit.yaml
  - snapshot-cronjob-controller.yaml
  - apply-ingress-whitelist-annotations.yaml
  - apply-ingress-auth-annotations.yaml
  - apply-ingress-external-dns-annotations.yaml
