---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/New_York"
  COREDNS_ADDR: "10.43.0.10"
  KUBE_API_ADDR: "10.30.30.150"
  CLUSTER_CIDR: "10.42.0.0/16"
  SERVICE_CIDR: "10.43.0.0/16"
  NODE_CIDR: "10.30.30.0/24"
  SVC_INGRESS_ADDR: "10.30.30.18"
  SVC_INTERNAL_INGRESS_ADDR: "10.30.30.17"
  SVC_PLEX_ADDR: "10.30.30.154"
  SVC_PROMTAIL_ADDR: "10.30.30.155"
  SVC_QBITTORRENT_ADDR: "10.30.30.156"
  SVC_LLDAP_ADDR: "10.30.30.157"
  SVC_INFLUXDB_ADDR: "10.30.30.159"
  SVC_LOKI_ADDR: "10.30.30.160"
  SVC_EMQX_ADDR: "10.30.30.162"
