---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: app-template
    releaseName: mqtt-air-sensor
    namespace: home
    repo: https://bjw-s.github.io/helm-charts/
    version: "1.4.0"
    valuesFile: values.yaml
